### PR TITLE
Change validations to use decorator, change color functions to allow tests

### PR DESCRIPTION
**Pull request by lawruble13**
Many small changes to styling to align with PEP 8, and changed validation of function parameters to use `@validate_args` decorator

### CODE REVIEW

**Comment by lawruble13** [comment]
Currently, there is an error with `parse_color` where `func_name` is being parsed as an argument, but isn't included in the type signature. Easy fix, commit pending conclusion of Slack discussion on validation philosophy

**Comment by lawruble13** [comment]
Resolves #43.

**Review by raduschirliu — CHANGES_REQUESTED** [review]
Has some merge conflicts, unfortunately :(

**Comment by lawruble13** [comment]
> Has some merge conflicts, unfortunately :(

Resolved.

**Review by raduschirliu — APPROVED** [review]

**Pull request merged**
